export const courses = [
	{
		id: 1,
		title: "Artificial Intelligence A-Z 2024: Build 7 AI + LLM & ML",
		description: `Join the AI revolution with our comprehensive course, covering the latest advancements in Artificial Intelligence! Learn to build 7 AI projects, including Large Language Models (LLMs) and ChatGPT, from scratch.\nOur expert instructors will guide you through the entire AI development process, from fundamentals to deployment.`,
		provider: "Learners hub inc.",
		totalHours: 4,
		lectures: 20,
		level: "Beginner",
		price: "N4,900",
		originalPrice: "N10,000",
		image: "/ai-course.svg",
		ratings: "/icons/ratings.svg",
		lastUpdated: "06/2024",
		certificateAvailable: true,
	},
	{
		id: 2,
		title: "Machine Learning Masterclass: Hands-On",
		description:
			"Join the AI revolution with our comprehensive course, covering the latest advancements in Artificial Intelligence! Learn to build 7 AI projects, including Large Language Models (LLMs) and ChatGPT, from scratch. Our expert instructors will guide you through the entire AI development process, from fundamentals to deployment.",
		provider: "Tech Academy",
		totalHours: 6,
		lectures: 25,
		level: "Intermediate",
		price: "N5,500",
		originalPrice: "N12,000",
		image: "/ai-course.svg",
		ratings: "/icons/ratings.svg",
		lastUpdated: "06/2024",
		certificateAvailable: false,
	},
	{
		id: 3,
		title: "Web Development Bootcamp: Complete Guide",
		description:
			"Join the AI revolution with our comprehensive course, covering the latest advancements in Artificial Intelligence! Learn to build 7 AI projects, including Large Language Models (LLMs) and ChatGPT, from scratch. Our expert instructors will guide you through the entire AI development process, from fundamentals to deployment.",

		provider: "Code School",
		totalHours: 10,
		lectures: 30,
		level: "All Levels",
		price: "N7,000",
		originalPrice: "N15,000",
		image: "/ai-course.svg",
		ratings: "/icons/ratings.svg",
		lastUpdated: "06/2024",
		certificateAvailable: false,
	},
	{
		id: 4,
		title: "Data Science and Analytics with Python",
		description:
			"Join the AI revolution with our comprehensive course, covering the latest advancements in Artificial Intelligence! Learn to build 7 AI projects, including Large Language Models (LLMs) and ChatGPT, from scratch. Our expert instructors will guide you through the entire AI development process, from fundamentals to deployment.",
		provider: "Data Inc.",
		totalHours: 8,
		lectures: 22,
		level: "Advanced",
		price: "N6,800",
		originalPrice: "N14,000",
		image: "/ai-course.svg",
		ratings: "/icons/ratings.svg",
		lastUpdated: "06/2024",
		certificateAvailable: true,
	},
	{
		id: 5,
		title: "Cybersecurity Fundamentals: Protect Your Network",
		description:
			"Join the AI revolution with our comprehensive course, covering the latest advancements in Artificial Intelligence! Learn to build 7 AI projects, including Large Language Models (LLMs) and ChatGPT, from scratch. Our expert instructors will guide you through the entire AI development process, from fundamentals to deployment.",
		provider: "Security Experts",
		totalHours: 5,
		lectures: 18,
		level: "Beginner",
		price: "N5,000",
		originalPrice: "N11,000",
		image: "/ai-course.svg",
		ratings: "/icons/ratings.svg",
		lastUpdated: "06/2024",
		certificateAvailable: false,
	},
];
